### PR TITLE
Added rename checks

### PR DESCRIPTION
**Pull request by gps137**
Forgot to add checks for renaming purposes. Now will check if a new-name already exists before renaming an Attribute or Class object.

### CODE REVIEW

**Comment by gps137** [comment]
Estimated time: .5 hours. Completion: 0.5 hours.

**Review by JonBear66 — CHANGES_REQUESTED** [review]
Everything looks good the only thing I can think if is adding a conditional for the textboxes in case someone submits " " as a text option. Unless I am mistaken that should be the only thing I would consider.

**Comment by gps137** [comment]
You're suggesting we require alphanumeric characters, then?

**Comment by gps137** [comment]
AlphaNumeric character requirement added. Ready for merging.

**Comment by JonBear66** [comment]
That looks good to me. Good work!

**Review by JonBear66 — APPROVED** [review]
Looks great

**Pull request merged**
